version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    volumes:
      - mysql_container:/var/lib/mysql:rw
    user: root
    restart: always
    ports:
      - 3308:3309
    environment:
      MYSQL_DATABASE: tpachatproject
      MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: ghassenmoallaa/categorieproduit
    ports:
      - 8089:8089
    restart: always
    container_name: spring_app
    environment:
     -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3309/tpachatproject?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
volumes:
  mysql_container: { }